# Generated by Django 4.0.3 on 2022-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='burn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=20)),
                ('Genre', models.CharField(max_length=20)),
                ('s1', models.CharField(max_length=20)),
                ('s2', models.CharField(max_length=20)),
                ('s3', models.CharField(max_length=20)),
                ('s4', models.CharField(max_length=20)),
                ('s5', models.CharField(max_length=20)),
                ('s6', models.CharField(max_length=20)),
                ('s7', models.CharField(max_length=20)),
                ('s8', models.CharField(max_length=20)),
                ('s9', models.CharField(max_length=20)),
                ('s10', models.CharField(max_length=20)),
                ('s11', models.CharField(max_length=20)),
                ('s12', models.CharField(max_length=20)),
                ('s13', models.CharField(max_length=20)),
                ('s14', models.CharField(max_length=20)),
                ('s15', models.CharField(max_length=20)),
                ('s16', models.CharField(max_length=20)),
                ('s17', models.CharField(max_length=20)),
                ('s18', models.CharField(max_length=20)),
                ('s19', models.CharField(max_length=20)),
                ('s20', models.CharField(max_length=20)),
                ('s21', models.CharField(max_length=20)),
            ],
        ),
    ]
