# Generated by Django 4.0.3 on 2022-03-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehermosa', '0002_alter_burn_age_alter_burn_genre_alter_burn_s1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='burn',
        ),
    ]
